export const ROUTES = {
  home: '/',
  shop: '/shop',
  product: (slug: string) => `/product/${slug}`,
  cart: '/cart',
  checkout: '/checkout',
  wishlist: '/wishlist',
  login: '/login',
  register: '/register',
  profile: '/profile',
  orders: '/profile/orders',
  admin: {
    root: '/admin',
    dashboard: '/admin',
    products: '/admin/products',
    categories: '/admin/categories',
    orders: '/admin/orders',
    customers: '/admin/customers',
    reviews: '/admin/reviews',
    banners: '/admin/banners',
    homepage: '/admin/homepage',
    media: '/admin/media',
    coupons: '/admin/coupons',
    settings: '/admin/settings',
  },
} as const
